import client from './client'

export const getGloryStatus       = ()           => client.get('/glory/status')
export const getCurrentGameweek   = ()           => client.get('/glory/gameweek')
export const getGloryGameweek     = (id)         => client.get(`/glory/gameweek/${id}`)
export const submitGloryPicks     = (id, picks)  => client.post(`/glory/gameweek/${id}/picks`, { picks })
export const getMyGloryPicks      = (id)         => client.get(`/glory/gameweek/${id}/picks`)
export const getGloryProfile      = ()           => client.get('/glory/profile')
export const getGloryLeaderboard  = (params)     => client.get('/glory/leaderboard', { params })
export const getGlorySprints       = ()           => client.get('/glory/sprints')
export const getGloryDivisions     = ()           => client.get('/glory/divisions')
export const getMyRelevantSprints  = ()           => client.get('/glory/sprints/my')
export const getCommunityPicks     = (id)         => client.get(`/glory/gameweek/${id}/community`)
export const getPublicProfile      = (userId)     => client.get(`/glory/users/${userId}`)
export const getFixtureStats       = (fixtureId)  => client.get(`/glory/fixtures/${fixtureId}/stats`)
export const getSprintDetail       = (sprintId)   => client.get(`/glory/sprints/${sprintId}`)
