import client from './client'

export const getMyLeagues        = ()               => client.get('/leagues')
export const createLeague        = (data)            => client.post('/leagues', data)
export const getLeague           = (id)              => client.get(`/leagues/${id}`)
export const updateLeague        = (id, data)        => client.put(`/leagues/${id}`, data)
export const joinLeague          = (code)            => client.post(`/leagues/join/${code}`)
export const getLeagueStandings  = (id)              => client.get(`/leagues/${id}/standings`)
export const toggleMemberPayment = (id, userId, has_paid) => client.put(`/leagues/${id}/members/${userId}/payment`, { has_paid })
export const leaveLeague         = (id)              => client.delete(`/leagues/${id}/leave`)
export const activateLeague      = (id)              => client.post(`/leagues/${id}/activate`)
export const getLeagueMatchup    = (id)              => client.get(`/leagues/${id}/matchup`)
export const submitLeaguePicks   = (id, picks)       => client.post(`/leagues/${id}/picks`, { picks })
export const getLeagueCalendar    = (id)              => client.get(`/leagues/${id}/calendar`)
export const getWeekMatchups      = (id, week)        => client.get(`/leagues/${id}/week/${week}/matchups`)
